name: PR

on:
    schedule:
        - cron: "*/10 * * * *"

jobs:
    label:
        name: Labeler
        runs-on: ubuntu-latest

        steps:
            - uses: docker://docker.io/ilyam8/periodic-pr-labeler:v0.1.1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  GITHUB_REPOSITORY: ${{ github.repository }}
                  LABEL_MAPPINGS_FILE: .github/labeler.yml
